Add JsonConverter(converters) option
google/json_serializable.dart pull request #1135
Opened 2022-04-21 11:40 UTC by rrousselGit

This implements what is described here https://github.com/google/json_serializable.dart/issues/1072#issuecomment-1104918300 (assuming this is desirable)

That should simplify a bit the work of having to reuse a few JsonConverter over and over by allowing folks to make a custom reusable annotation or write things like:

```dart
const myConverters = [DocumentReferenceConverter()];

@JsonSerializable(converters: myConverters);
```

2022-04-21 11:42 UTC, rrousselGit commented
I had to separate ClassConfig and JsonSerializable for this (because ClassConfig receives DartObjects for the converters but JsonSerializable receives a JsonConverter).

Hopefully that's alright.

2022-04-26 21:58 UTC, kevmoo commented
> I had to separate ClassConfig and JsonSerializable for this (because ClassConfig receives DartObjects for the converters but JsonSerializable receives a JsonConverter).
> 
> Hopefully that's alright.

Ha! We'll start by seeing if the tests pass. 😁

2022-04-27 10:13 UTC, rrousselGit commented
The CI just wanted a dependency_overrides for the annotation 😄

2022-04-28 21:26 UTC, kevmoo commented on json_serializable/test/kitchen_sink/kitchen_sink.g_exclude_null.dart
> -@durationConverter
I'd like to keep one example of using a constant. Do we still have one?

2022-05-05 03:37 UTC, kevmoo commented on json_serializable/lib/src/type_helpers/config_types.dart
> +class ClassConfig {
This refactoring is my least favorite change.

Did you ponder just leaving `converters` empty and adding a property here?

2022-05-06 19:54 UTC, kevmoo requested changes

2022-05-06 19:54 UTC, kevmoo commented on json_annotation/lib/src/json_serializable.dart
> +import 'json_converter.dart';
Need to bump the minor version of this package. Add a changelog entry.

2022-05-06 19:54 UTC, kevmoo commented on json_serializable/pubspec.yaml
> +dependency_overrides:
Need to bump the version range on `json_annotation` to be "tight" w/ what you change in the json_annotation package

2022-05-06 19:54 UTC, kevmoo commented on json_serializable/pubspec.yaml
> +dependency_overrides:
also changelog!

2022-05-09 11:05 UTC, rrousselGit commented
I'm not quite sure how to fix that last CI error

One test seems to complain if I don't update the readme with 4.6.0 links. But the markdown checked complains that 4.6.0 links are 404 (which is logical since it isn't published yet)

2022-05-24 02:53 UTC, kevmoo commented
ignore the markdown errors. That's expected when things are revved!

2022-05-24 02:54 UTC, kevmoo approved these changes
Sweet!

2022-05-24 02:55 UTC, merged