Add JsonSerializable.createPerFieldToJson
google/json_serializable.dart pull request #1230
Opened 2022-10-25 14:36 UTC by rrousselGit

closes #1198.

As per #1198, this PR generates an abstract `_$MyModelPerFieldToJson` to allow the encoding of one specific property

2022-10-26 08:50 UTC, rrousselGit commented
@kevmoo This should be good for review. I've rebased it with #1232. Just in case, you can look at the commit tab to review changes specific to this PR

2022-11-02 00:04 UTC, kevmoo requested changes
Overall looks good. Don't worry about the separate PRs for the little bits...unless you want to!

2022-11-02 00:04 UTC, kevmoo commented on json_serializable/lib/src/encoder_helper.dart
> +  bool _canWriteJsonWithoutNullCheck(FieldElement field) {
That IS a better name, but in general I'd love these tiny tweaks to be seperate PRs – easier to read things!

2022-11-02 00:04 UTC, kevmoo commented on json_serializable/lib/src/helper_core.dart
> +  String genericClassArgumentsImpl({required bool withConstraints}) =>
Ditto. I LOVE this refactor. Try to pull this out as tiny PRs. Just makes reviewing easier!

2022-11-02 00:04 UTC, kevmoo commented on json_serializable/test/integration/create_per_field_to_json_example.g.dart
> +// ignore: unused_element
Seems like the formatter doesn't help with these. In that case, it might be good if YOU indent them in the output

2022-11-03 14:19 UTC, kevmoo approved these changes

2022-11-03 14:19 UTC, kevmoo commented on json_serializable/CHANGELOG.md
> +- Require `json_annotation: '>=4.8.0 <4.9.0'`
add "support new xyz feature"

2022-11-03 14:19 UTC, merged