Upgrade analyzer to 5.2.0 and fix deprecated warnings
google/json_serializable.dart pull request #1232
Opened 2022-10-26 07:15 UTC by rrousselGit

The CI is currently failing due to the new 5.2.0 version of analyzer deprecating a bunch of methods.

2022-10-26 20:42 UTC, kevmoo requested changes

2022-10-26 20:42 UTC, kevmoo commented on json_annotation/CHANGELOG.md
> +- Require Dart SDK `>=2.18.0`.
4.7.1 hasn't been shipped yet (hence the -dev) – so you can put this in the blew section

2022-10-26 20:42 UTC, kevmoo commented on json_annotation/pubspec.yaml
> +version: 4.7.2-dev+1
revert this

2022-10-26 20:42 UTC, kevmoo commented on json_serializable/pubspec.yaml
> +version: 6.6.0-dev
6.5.5-dev is better. No new features – just bumping the SDK constraint

2022-10-26 20:42 UTC, kevmoo commented on checked_yaml/pubspec.yaml
> +  sdk: '>=2.18.0 <3.0.0'
need a changelog update here ,too!

2022-10-27 09:44 UTC, rrousselGit commented
Done, I've updated them all

2022-10-27 16:19 UTC, kevmoo approved these changes

2022-10-27 16:19 UTC, merged